language: go
go:
 - tip

stages:
 - test
 - deploy

before_install:

jobs:
  include:
    - stage: test
      script: make deps
      script: make test
      script: make build
    - stage: deploy
      if: type NOT IN (push, pull_request) AND \
          branch = master
      script: make deps
      script: make test
      script: make build
      script: make get-version

