# Golang CircleCI 2.1 configuration file
version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/rdoorn/ixxi

jobs:
  test:
    executor: golang
    steps:
      - checkout

      - run: make deps
      - run: make test
      - run: make coverage
      - run: make coverage-upload

  release:
    executor: golang
    steps:
      - checkout

      - run: make deps

      - run: 
          name: "Publish Release on GitHub - if merge to master"
          command: ./tools/ci-package.sh

  automated-golang-version:
    executor: golang
    steps:
      - checkout

      - run: make deps

      - run:
          name: "Publish Release on GitHub - if new golang version"
          command: ./tools/golang-update.sh


  ok:
    executor: golang
    steps:
      - checkout

workflows:
  version: 2

  build_test_package:
    jobs:
      - test:
          filters:
            branches:
              ignore: /documentation-.*/
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
      - ok:
          requires:
            - test
            - release

  scheduled-golang-update-check:
    triggers:
      - schedule:
          cron: "45 13 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - automated-golang-version:
          requires:
            - test

