# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang

    working_directory: /go/src/github.com/rdoorn/ixxi
    branches:
      ignore:
        - master
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      # - run: go get -v -t -d ./...
      - run: env
      - run: make deps
      - run: make test
      - run: make get-version
      - run: make build

  build:
    docker:
      # specify the version
      - image: circleci/golang

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/rdoorn/ixxi
    branches:
      only:
        - master
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      # - run: go get -v -t -d ./...
      - run: make deps
      - run: make test
      - run: make get-version
      - run: make build
      - run: 
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(cat .version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/packages/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

