# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang

    working_directory: /go/src/github.com/rdoorn/ixxi
    steps:
      - checkout

      - run: SOURCE_BRANCH="<<pipeline.pull_request.source_branch>>"
      - run: env
      - run: make deps
      - run: make test
      - run: make build

      - run: 
          name: "Publish Release on GitHub"
          command: ./tools/ci-package.sh

