# Golang CircleCI 2.1 configuration file
version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/rdoorn/ixxi

jobs:
  test:
    executor: golang
    steps:
      - checkout

      - run: env
      - run: make deps
      - run: make test
      - run: make coverage
      - run: make coverage-upload
      - run: make build

  release:
    executor: golang
    steps:
      - checkout

      - run: env
      - run: make deps

      - run: 
          name: "Publish Release on GitHub"
          command: ./tools/ci-package.sh

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only:
                - master
